// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Migraciones por la conexión directa (puerto 5432). El pooler de transacciones
    // (6543) no soporta las sentencias DDL que ejecuta `prisma migrate`.
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
